package com.android.settings.core.gateway;

import com.android.settings.DateTimeSettings;
import com.android.settings.DeviceAdminSettings;
import com.android.settings.DisplaySettings;
import com.android.settings.IccLockSettings;
import com.android.settings.LegalSettings;
import com.android.settings.MasterClear;
import com.android.settings.PrivacySettings;
import com.android.settings.Settings.AccessibilitySettingsActivity;
import com.android.settings.Settings.AccountDashboardActivity;
import com.android.settings.Settings.AdvancedAppsActivity;
import com.android.settings.Settings.AppAndNotificationDashboardActivity;
import com.android.settings.Settings.BluetoothSettingsActivity;
import com.android.settings.Settings.ConfigureNotificationSettingsActivity;
import com.android.settings.Settings.ConnectedDeviceDashboardActivity;
import com.android.settings.Settings.DataUsageSummaryActivity;
import com.android.settings.Settings.DateTimeSettingsActivity;
import com.android.settings.Settings.DeviceInfoSettingsActivity;
import com.android.settings.Settings.DisplaySettingsActivity;
import com.android.settings.Settings.EnterprisePrivacySettingsActivity;
import com.android.settings.Settings.LanguageAndInputSettingsActivity;
import com.android.settings.Settings.LocationSettingsActivity;
import com.android.settings.Settings.ManageApplicationsActivity;
import com.android.settings.Settings.MyDeviceInfoActivity;
import com.android.settings.Settings.NetworkDashboardActivity;
import com.android.settings.Settings.OPAboutPhoneActivity;
import com.android.settings.Settings.OPBluetoothCarKitActivity;
import com.android.settings.Settings.OPCloudServiceSettings;
import com.android.settings.Settings.OPDeviceNameActivity;
import com.android.settings.Settings.OPToolsSettingsActivity;
import com.android.settings.Settings.OPVoiceAssistantSettingsActivity;
import com.android.settings.Settings.PaymentSettingsActivity;
import com.android.settings.Settings.PowerUsageSummaryActivity;
import com.android.settings.Settings.PrintSettingsActivity;
import com.android.settings.Settings.SecurityDashboardActivity;
import com.android.settings.Settings.SimSettingsActivity;
import com.android.settings.Settings.SoundSettingsActivity;
import com.android.settings.Settings.StorageDashboardActivity;
import com.android.settings.Settings.SystemDashboardActivity;
import com.android.settings.Settings.UserSettingsActivity;
import com.android.settings.Settings.WifiDisplaySettingsActivity;
import com.android.settings.Settings.WifiSettingsActivity;
import com.android.settings.TestingSettings;
import com.android.settings.TetherSettings;
import com.android.settings.TrustedCredentialsSettings;
import com.android.settings.accessibility.AccessibilitySettings;
import com.android.settings.accessibility.AccessibilitySettingsForSetupWizard;
import com.android.settings.accessibility.CaptionPropertiesFragment;
import com.android.settings.accessibility.ToggleDaltonizerPreferenceFragment;
import com.android.settings.accounts.AccountDashboardFragment;
import com.android.settings.accounts.AccountSyncSettings;
import com.android.settings.accounts.ChooseAccountActivity;
import com.android.settings.accounts.ManagedProfileSettings;
import com.android.settings.applications.AppAndNotificationDashboardFragment;
import com.android.settings.applications.DefaultAppSettings;
import com.android.settings.applications.DirectoryAccessDetails;
import com.android.settings.applications.ManageDomainUrls;
import com.android.settings.applications.ProcessStatsSummary;
import com.android.settings.applications.ProcessStatsUi;
import com.android.settings.applications.UsageAccessDetails;
import com.android.settings.applications.VrListenerSettings;
import com.android.settings.applications.appinfo.AppInfoDashboardFragment;
import com.android.settings.applications.appinfo.DrawOverlayDetails;
import com.android.settings.applications.appinfo.ExternalSourcesDetails;
import com.android.settings.applications.appinfo.PictureInPictureDetails;
import com.android.settings.applications.appinfo.PictureInPictureSettings;
import com.android.settings.applications.appinfo.WriteSettingsDetails;
import com.android.settings.applications.appops.BackgroundCheckSummary;
import com.android.settings.applications.assist.DefaultAssistPicker;
import com.android.settings.applications.assist.ManageAssist;
import com.android.settings.applications.manageapplications.ManageApplications;
import com.android.settings.backup.ToggleBackupSettingFragment;
import com.android.settings.bluetooth.BluetoothDeviceDetailsFragment;
import com.android.settings.connecteddevice.AdvancedConnectedDeviceDashboardFragment;
import com.android.settings.connecteddevice.ConnectedDeviceDashboardFragment;
import com.android.settings.connecteddevice.OPBluetoothCarKitDashboardFragment;
import com.android.settings.connecteddevice.PreviouslyConnectedDeviceDashboardFragment;
import com.android.settings.connecteddevice.usb.UsbDetailsFragment;
import com.android.settings.datausage.DataSaverSummary;
import com.android.settings.datausage.DataUsageList;
import com.android.settings.datausage.DataUsageSummary;
import com.android.settings.datausage.DataUsageSummaryLegacy;
import com.android.settings.deletionhelper.AutomaticStorageManagerSettings;
import com.android.settings.development.DevelopmentSettingsDashboardFragment;
import com.android.settings.deviceinfo.DeviceInfoSettings;
import com.android.settings.deviceinfo.PrivateVolumeForget;
import com.android.settings.deviceinfo.PrivateVolumeSettings;
import com.android.settings.deviceinfo.PublicVolumeSettings;
import com.android.settings.deviceinfo.StorageDashboardFragment;
import com.android.settings.deviceinfo.StorageSettings;
import com.android.settings.deviceinfo.aboutphone.MyDeviceInfoFragment;
import com.android.settings.display.NightDisplaySettings;
import com.android.settings.dream.DreamSettings;
import com.android.settings.enterprise.EnterprisePrivacySettings;
import com.android.settings.fuelgauge.AdvancedPowerUsageDetail;
import com.android.settings.fuelgauge.PowerUsageAdvanced;
import com.android.settings.fuelgauge.PowerUsageSummary;
import com.android.settings.fuelgauge.batterysaver.BatterySaverSettings;
import com.android.settings.gestures.AssistGestureSettings;
import com.android.settings.gestures.DoubleTapPowerSettings;
import com.android.settings.gestures.DoubleTapScreenSettings;
import com.android.settings.gestures.DoubleTwistGestureSettings;
import com.android.settings.gestures.PickupGestureSettings;
import com.android.settings.gestures.SwipeToNotificationSettings;
import com.android.settings.gestures.SwipeUpGestureSettings;
import com.android.settings.inputmethod.AvailableVirtualKeyboardFragment;
import com.android.settings.inputmethod.KeyboardLayoutPickerFragment;
import com.android.settings.inputmethod.PhysicalKeyboardFragment;
import com.android.settings.inputmethod.SpellCheckersSettings;
import com.android.settings.inputmethod.UserDictionaryList;
import com.android.settings.inputmethod.UserDictionarySettings;
import com.android.settings.language.LanguageAndInputSettings;
import com.android.settings.localepicker.LocaleListEditor;
import com.android.settings.location.LocationSettings;
import com.android.settings.location.ScanningSettings;
import com.android.settings.network.ApnEditor;
import com.android.settings.network.ApnSettings;
import com.android.settings.network.NetworkDashboardFragment;
import com.android.settings.nfc.AndroidBeam;
import com.android.settings.nfc.PaymentSettings;
import com.android.settings.notification.AppNotificationSettings;
import com.android.settings.notification.ChannelGroupNotificationSettings;
import com.android.settings.notification.ChannelNotificationSettings;
import com.android.settings.notification.ConfigureNotificationSettings;
import com.android.settings.notification.NotificationAccessSettings;
import com.android.settings.notification.NotificationStation;
import com.android.settings.notification.SoundSettings;
import com.android.settings.notification.ZenAccessSettings;
import com.android.settings.notification.ZenModeAutomationSettings;
import com.android.settings.notification.ZenModeBlockedEffectsSettings;
import com.android.settings.notification.ZenModeEventRuleSettings;
import com.android.settings.notification.ZenModeScheduleRuleSettings;
import com.android.settings.notification.ZenModeSettings;
import com.android.settings.password.ChooseLockPassword.ChooseLockPasswordFragment;
import com.android.settings.password.ChooseLockPattern.ChooseLockPatternFragment;
import com.android.settings.print.PrintJobSettingsFragment;
import com.android.settings.print.PrintSettingsFragment;
import com.android.settings.security.CryptKeeperSettings;
import com.android.settings.security.LockscreenDashboardFragment;
import com.android.settings.security.SecuritySettings;
import com.android.settings.sim.SimSettings;
import com.android.settings.support.SupportDashboardActivity;
import com.android.settings.system.ResetDashboardFragment;
import com.android.settings.system.SystemDashboardFragment;
import com.android.settings.tts.TextToSpeechSettings;
import com.android.settings.users.UserSettings;
import com.android.settings.vpn2.VpnSettings;
import com.android.settings.wallpaper.WallpaperTypeSettings;
import com.android.settings.webview.WebViewAppPicker;
import com.android.settings.wfd.WifiDisplaySettings;
import com.android.settings.wifi.ConfigureWifiSettings;
import com.android.settings.wifi.SavedAccessPointsWifiSettings;
import com.android.settings.wifi.WifiAPITest;
import com.android.settings.wifi.WifiInfo;
import com.android.settings.wifi.WifiSettings;
import com.android.settings.wifi.calling.WifiCallingSettings;
import com.android.settings.wifi.p2p.WifiP2pSettings;
import com.oneplus.lib.util.AnimatorUtils;
import com.oneplus.settings.OPButtonsAndGesturesSettings;
import com.oneplus.settings.OPCustomFingerprintAnimSettings;
import com.oneplus.settings.OPDeviceName;
import com.oneplus.settings.OPGestureAnswerSettings;
import com.oneplus.settings.aboutphone.OPAboutPhone;
import com.oneplus.settings.backgroundoptimize.BgOptimizeApps;
import com.oneplus.settings.backgroundoptimize.funcswitch.BgOptimizeSwitch;
import com.oneplus.settings.better.OPAppLocker;
import com.oneplus.settings.better.OPGamingMode;
import com.oneplus.settings.better.OPHapticFeedback;
import com.oneplus.settings.better.OPNightMode;
import com.oneplus.settings.better.OPReadingMode;
import com.oneplus.settings.carcharger.OPCarChargerSettings;
import com.oneplus.settings.displaysizeadaption.DisplaySizeAdaptionApps;
import com.oneplus.settings.faceunlock.OPFaceUnlockSettings;
import com.oneplus.settings.im.OPQuickReplySettings;
import com.oneplus.settings.notification.OPEarphoneMode;
import com.oneplus.settings.notification.OPNotificationAndNotdisturb;
import com.oneplus.settings.notification.OPRingPattern;
import com.oneplus.settings.notification.OPSilentMode;
import com.oneplus.settings.notification.OPVibrationMode;
import com.oneplus.settings.others.OPToolsSettings;
import com.oneplus.settings.product.OPPreInstalledAppList;
import com.oneplus.settings.product.OPProductInfoSettings;
import com.oneplus.settings.quicklaunch.OPQuickLaunchListSettings;
import com.oneplus.settings.quicklaunch.OPQuickLaunchSettings;
import com.oneplus.settings.quickpay.QuickPaySettings;
import com.oneplus.settings.system.OPRamBoostSettings;

public class SettingsGateway {
    public static final String[] ENTRY_FRAGMENTS;
    public static final String[] SETTINGS_FOR_RESTRICTED = new String[]{NetworkDashboardActivity.class.getName(), ConnectedDeviceDashboardActivity.class.getName(), AppAndNotificationDashboardActivity.class.getName(), DisplaySettingsActivity.class.getName(), SoundSettingsActivity.class.getName(), StorageDashboardActivity.class.getName(), PowerUsageSummaryActivity.class.getName(), AccountDashboardActivity.class.getName(), SecurityDashboardActivity.class.getName(), AccessibilitySettingsActivity.class.getName(), OPToolsSettingsActivity.class.getName(), OPCloudServiceSettings.class.getName(), OPVoiceAssistantSettingsActivity.class.getName(), SystemDashboardActivity.class.getName(), SupportDashboardActivity.class.getName(), WifiSettingsActivity.class.getName(), DataUsageSummaryActivity.class.getName(), SimSettingsActivity.class.getName(), BluetoothSettingsActivity.class.getName(), WifiDisplaySettingsActivity.class.getName(), PrintSettingsActivity.class.getName(), UserSettingsActivity.class.getName(), ConfigureNotificationSettingsActivity.class.getName(), AdvancedAppsActivity.class.getName(), ManageApplicationsActivity.class.getName(), PaymentSettingsActivity.class.getName(), LocationSettingsActivity.class.getName(), LanguageAndInputSettingsActivity.class.getName(), DateTimeSettingsActivity.class.getName(), DeviceInfoSettingsActivity.class.getName(), EnterprisePrivacySettingsActivity.class.getName(), MyDeviceInfoActivity.class.getName(), OPAboutPhoneActivity.class.getName(), OPBluetoothCarKitActivity.class.getName()};

    static {
        String[] strArr = new String[Const.CODE_C1_DF0];
        strArr[0] = AdvancedConnectedDeviceDashboardFragment.class.getName();
        strArr[1] = WifiSettings.class.getName();
        strArr[2] = ConfigureWifiSettings.class.getName();
        strArr[3] = SavedAccessPointsWifiSettings.class.getName();
        strArr[4] = SimSettings.class.getName();
        strArr[5] = TetherSettings.class.getName();
        strArr[6] = WifiP2pSettings.class.getName();
        strArr[7] = BackgroundCheckSummary.class.getName();
        strArr[8] = VpnSettings.class.getName();
        strArr[9] = DateTimeSettings.class.getName();
        strArr[10] = LocaleListEditor.class.getName();
        strArr[11] = AvailableVirtualKeyboardFragment.class.getName();
        strArr[12] = LanguageAndInputSettings.class.getName();
        strArr[13] = SpellCheckersSettings.class.getName();
        strArr[14] = UserDictionaryList.class.getName();
        strArr[15] = UserDictionarySettings.class.getName();
        strArr[16] = DisplaySettings.class.getName();
        strArr[17] = DeviceInfoSettings.class.getName();
        strArr[18] = MyDeviceInfoFragment.class.getName();
        strArr[19] = ManageApplications.class.getName();
        strArr[20] = ManageAssist.class.getName();
        strArr[21] = ProcessStatsUi.class.getName();
        strArr[22] = NotificationStation.class.getName();
        strArr[23] = LocationSettings.class.getName();
        strArr[24] = ScanningSettings.class.getName();
        strArr[25] = SecuritySettings.class.getName();
        strArr[26] = UsageAccessDetails.class.getName();
        strArr[27] = PrivacySettings.class.getName();
        strArr[28] = DeviceAdminSettings.class.getName();
        strArr[29] = AccessibilitySettings.class.getName();
        strArr[30] = AccessibilitySettingsForSetupWizard.class.getName();
        strArr[31] = CaptionPropertiesFragment.class.getName();
        strArr[32] = ToggleDaltonizerPreferenceFragment.class.getName();
        strArr[33] = TextToSpeechSettings.class.getName();
        strArr[34] = StorageSettings.class.getName();
        strArr[35] = PrivateVolumeForget.class.getName();
        strArr[36] = PrivateVolumeSettings.class.getName();
        strArr[37] = PublicVolumeSettings.class.getName();
        strArr[38] = DevelopmentSettingsDashboardFragment.class.getName();
        strArr[39] = AndroidBeam.class.getName();
        strArr[40] = WifiDisplaySettings.class.getName();
        strArr[41] = PowerUsageSummary.class.getName();
        strArr[42] = PowerUsageAdvanced.class.getName();
        strArr[43] = AccountSyncSettings.class.getName();
        strArr[44] = AssistGestureSettings.class.getName();
        strArr[45] = SwipeToNotificationSettings.class.getName();
        strArr[46] = DoubleTapPowerSettings.class.getName();
        strArr[47] = DoubleTapScreenSettings.class.getName();
        strArr[48] = PickupGestureSettings.class.getName();
        strArr[49] = DoubleTwistGestureSettings.class.getName();
        strArr[50] = SwipeUpGestureSettings.class.getName();
        strArr[51] = CryptKeeperSettings.class.getName();
        strArr[52] = DataUsageSummary.class.getName();
        strArr[53] = DataUsageSummaryLegacy.class.getName();
        strArr[54] = DreamSettings.class.getName();
        strArr[55] = UserSettings.class.getName();
        strArr[56] = NotificationAccessSettings.class.getName();
        strArr[57] = ZenAccessSettings.class.getName();
        strArr[58] = ZenModeAutomationSettings.class.getName();
        strArr[59] = PrintSettingsFragment.class.getName();
        strArr[60] = PrintJobSettingsFragment.class.getName();
        strArr[61] = TrustedCredentialsSettings.class.getName();
        strArr[62] = PaymentSettings.class.getName();
        strArr[63] = KeyboardLayoutPickerFragment.class.getName();
        strArr[64] = PhysicalKeyboardFragment.class.getName();
        strArr[65] = ZenModeSettings.class.getName();
        strArr[66] = SoundSettings.class.getName();
        strArr[67] = ConfigureNotificationSettings.class.getName();
        strArr[68] = ChooseLockPasswordFragment.class.getName();
        strArr[69] = ChooseLockPatternFragment.class.getName();
        strArr[70] = AppInfoDashboardFragment.class.getName();
        strArr[71] = BatterySaverSettings.class.getName();
        strArr[72] = AppNotificationSettings.class.getName();
        strArr[73] = ChannelNotificationSettings.class.getName();
        strArr[74] = ChannelGroupNotificationSettings.class.getName();
        strArr[75] = ApnSettings.class.getName();
        strArr[76] = ApnEditor.class.getName();
        strArr[77] = WifiCallingSettings.class.getName();
        strArr[78] = ZenModeScheduleRuleSettings.class.getName();
        strArr[79] = ZenModeEventRuleSettings.class.getName();
        strArr[80] = ZenModeBlockedEffectsSettings.class.getName();
        strArr[81] = ProcessStatsUi.class.getName();
        strArr[82] = AdvancedPowerUsageDetail.class.getName();
        strArr[83] = ProcessStatsSummary.class.getName();
        strArr[84] = DrawOverlayDetails.class.getName();
        strArr[85] = WriteSettingsDetails.class.getName();
        strArr[86] = ExternalSourcesDetails.class.getName();
        strArr[87] = DefaultAppSettings.class.getName();
        strArr[88] = WallpaperTypeSettings.class.getName();
        strArr[89] = VrListenerSettings.class.getName();
        strArr[90] = PictureInPictureSettings.class.getName();
        strArr[91] = PictureInPictureDetails.class.getName();
        strArr[92] = ManagedProfileSettings.class.getName();
        strArr[93] = ChooseAccountActivity.class.getName();
        strArr[94] = IccLockSettings.class.getName();
        strArr[95] = TestingSettings.class.getName();
        strArr[96] = WifiAPITest.class.getName();
        strArr[97] = WifiInfo.class.getName();
        strArr[98] = MasterClear.class.getName();
        strArr[99] = ResetDashboardFragment.class.getName();
        strArr[100] = NightDisplaySettings.class.getName();
        strArr[101] = ManageDomainUrls.class.getName();
        strArr[102] = AutomaticStorageManagerSettings.class.getName();
        strArr[103] = StorageDashboardFragment.class.getName();
        strArr[104] = SystemDashboardFragment.class.getName();
        strArr[105] = NetworkDashboardFragment.class.getName();
        strArr[106] = ConnectedDeviceDashboardFragment.class.getName();
        strArr[107] = UsbDetailsFragment.class.getName();
        strArr[108] = AppAndNotificationDashboardFragment.class.getName();
        strArr[109] = AccountDashboardFragment.class.getName();
        strArr[110] = EnterprisePrivacySettings.class.getName();
        strArr[111] = WebViewAppPicker.class.getName();
        strArr[112] = LockscreenDashboardFragment.class.getName();
        strArr[113] = BluetoothDeviceDetailsFragment.class.getName();
        strArr[114] = DataUsageList.class.getName();
        strArr[115] = DirectoryAccessDetails.class.getName();
        strArr[116] = ToggleBackupSettingFragment.class.getName();
        strArr[117] = PreviouslyConnectedDeviceDashboardFragment.class.getName();
        strArr[118] = OPFaceUnlockSettings.class.getName();
        strArr[119] = OPGestureAnswerSettings.class.getName();
        strArr[120] = OPToolsSettings.class.getName();
        strArr[121] = QuickPaySettings.class.getName();
        strArr[122] = OPGamingMode.class.getName();
        strArr[123] = DefaultAssistPicker.class.getName();
        strArr[124] = OPAppLocker.class.getName();
        strArr[125] = OPPreInstalledAppList.class.getName();
        strArr[SecuritySettings.CHANGE_TRUST_AGENT_SETTINGS] = OPProductInfoSettings.class.getName();
        strArr[127] = OPHapticFeedback.class.getName();
        strArr[128] = OPRamBoostSettings.class.getName();
        strArr[129] = DisplaySizeAdaptionApps.class.getName();
        strArr[130] = OPEarphoneMode.class.getName();
        strArr[Const.CODE_C1_CW3] = OPNotificationAndNotdisturb.class.getName();
        strArr[Const.CODE_C1_CW4] = OPButtonsAndGesturesSettings.class.getName();
        strArr[Const.CODE_C1_CW5] = OPRingPattern.class.getName();
        strArr[Const.CODE_C1_CW6] = OPSilentMode.class.getName();
        strArr[135] = OPVibrationMode.class.getName();
        strArr[136] = OPDeviceName.class.getName();
        strArr[Const.CODE_C1_DSW] = OPDeviceNameActivity.class.getName();
        strArr[Const.CODE_C1_HDW] = OPNightMode.class.getName();
        strArr[Const.CODE_C1_TGW] = OPReadingMode.class.getName();
        strArr[Const.CODE_C1_DLW] = DataSaverSummary.class.getName();
        strArr[Const.CODE_C1_DLY] = BgOptimizeApps.class.getName();
        strArr[Const.CODE_C1_DLC] = BgOptimizeSwitch.class.getName();
        strArr[143] = OPQuickLaunchSettings.class.getName();
        strArr[Const.CODE_C1_SPA] = OPQuickLaunchListSettings.class.getName();
        strArr[Const.CODE_C1_SPC] = OPAboutPhone.class.getName();
        strArr[Const.CODE_C1_SPL] = LegalSettings.class.getName();
        strArr[147] = MyDeviceInfoFragment.class.getName();
        strArr[148] = OPCustomFingerprintAnimSettings.class.getName();
        strArr[149] = OPCarChargerSettings.class.getName();
        strArr[AnimatorUtils.time_part4] = OPQuickReplySettings.class.getName();
        strArr[Const.CODE_C1_SWA] = OPBluetoothCarKitDashboardFragment.class.getName();
        ENTRY_FRAGMENTS = strArr;
    }
}
